<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<RootNamespace>Holiday_Explorer</RootNamespace>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="HolidayExplorer.Core\**\*.cs" />
		<Compile Remove="HolidayExplorer.WebHost\**\*.cs" />

		<EmbeddedResource Remove="HolidayExplorer.Core\**" />
		<EmbeddedResource Remove="HolidayExplorer.WebHost\**" />

		<None Remove="HolidayExplorer.Core\**" />
		<None Remove="HolidayExplorer.WebHost\**" />

		<Page Remove="HolidayExplorer.Core\**\*.xaml" />
		<Page Remove="HolidayExplorer.WebHost\**\*.xaml" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Assets\Map\map.css" />
		<None Remove="Assets\Map\map.html" />
		<None Remove="Assets\Map\map.js" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="Data\holidays.seed.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Include="Assets\Map\map.css">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Include="Assets\Map\map.html">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>

		<Content Include="Assets\Map\map.js">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="HolidayExplorer.Core\HolidayExplorer.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Core\Interfaces\" />
		<Folder Include="Infrastructure\" />
		<Folder Include="MVVM\UserControls\" />
		<Folder Include="Features\" />
		<Folder Include="Shared\Helpers\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
	</ItemGroup>

</Project>