<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>Holiday_Explorer</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Core\Interfaces\" />
    <Folder Include="MVVM\Core\" />
    <Folder Include="MVVM\UserControls\" />
    <Folder Include="MVVM\ViewModels\" />
    <Folder Include="Features\" />
    <Folder Include="Shared\Helpers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.3.2" />
  </ItemGroup>

</Project>
