<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>HolidayExplorer.WebHost</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\HolidayExplorer.Core\HolidayExplorer.Core.csproj" />
	</ItemGroup>

</Project>